apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rook-ceph
  name: rook-ceph-object-secrets-configmap
data:
  access_key: N3UDX9XCXPCZ1WN55E7S
  secrets_key: xbm8X8oedVGSvzlthEbgPSOuSjtPRjaG8eA62B0K
  endpoint: rook-ceph-rgw-my-store.rook-ceph
