apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      name: admin
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: image-store
          mountPath: /html
      volumes:
      - name: image-store
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs 
            clusterNamespace: rook-ceph 

